"""empty message

Revision ID: 3d1fce69d1b2
Revises: b75d6255692e
Create Date: 2019-12-15 14:23:27.264461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d1fce69d1b2'
down_revision = 'b75d6255692e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('goods', 'sale',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('goods', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('goods', 'view',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='浏览次数')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'view',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='浏览次数')
    op.alter_column('goods', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('goods', 'sale',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('goods', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
