"""empty message

Revision ID: a908c6e35e4a
Revises: d99464c4873a
Create Date: 2019-12-15 14:21:32.093525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a908c6e35e4a'
down_revision = 'd99464c4873a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('detail', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('sale', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('view', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='浏览次数'),
    sa.Column('img', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('imgs', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('state', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True, comment='审核状态, 0待审核, 1审核通过, 2不通过'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='goods_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
