"""empty message

Revision ID: b1b1001ca6b2
Revises: d5e5ebe84e91
Create Date: 2019-12-15 21:02:40.488869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b1001ca6b2'
down_revision = 'd5e5ebe84e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'goods', ['order_id'], ['id'])
    op.drop_column('comment', 'goods_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'goods', ['goods_id'], ['id'])
    op.drop_column('comment', 'order_id')
    # ### end Alembic commands ###
