"""empty message

Revision ID: b75d6255692e
Revises: a908c6e35e4a
Create Date: 2019-12-15 14:22:25.440487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b75d6255692e'
down_revision = 'a908c6e35e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True, comment='浏览次数'),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('imgs', sa.Text(), nullable=False),
    sa.Column('state', mysql.TINYINT(), nullable=True, comment='审核状态, 0待审核, 1审核通过, 2不通过'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
